import Footer from '@/components/ui/Footer';
import Header from '@/components/ui/Header';
import Sidebar from '@/components/ui/Sidebar';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Suspense } from 'react';
import './globals.css';
import Loading from './loading';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Header />
        <main>
          <Sidebar />
          <Suspense fallback={<Loading />}>
            <div className='content'>{children}</div>
          </Suspense>
        </main>
        <Footer />
      </body>
    </html>
  );
}
